version: "3.4"

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/src
    environment:
      - PYTHONUNBUFFERED=True
