# Generated by Django 2.2.6 on 2019-10-20 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks_samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoverUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batery', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='rocksample',
            name='composition',
            field=models.CharField(max_length=1000),
        ),
    ]
